### ISSUE TITLE
update GHA branch to `main`?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos.github.io#5]
In reference to https://github.com/ioos/documentation-theme-jekyll/issues/3#issuecomment-1442523171, we should adjust `gh-pages` to `main` if you want the action to run on any pushes to the markdown files. 

https://github.com/ioos/ioos.github.io/blob/270e0ac35732133c50baf1775a8d99e31e143b6e/.github/workflows/sync_theme.yml#L5

The other option is to change the branch `main` to `gh-pages` (which is consistent with how our other doc only repos do it, like the [ncei-archiving-cookbook](https://github.com/ioos/ncei-archiving-cookbook)). Then, we have to update the Pages setting to state we are serving from `gh-pages` branch.
![image](https://user-images.githubusercontent.com/8480023/221193847-4d67bcc3-5b10-4780-9e07-9204cbe653c1.png)

**Comment by MathewBiddle** [comment]
Amount of effort is similar for both options. I vote for the later (renaming `main` to `gh-pages`).

**Comment by mwengren** [comment]
I guess I prefer to change the workflow file and leave the `main` branch as is so we follow the GitHub convention for serving the 'root' ioos.github.io GH pages site from main.  Maybe it's a legacy thing now since you have to option to designate a branch, but at one point they didn't offer that...

I'll just push a change in the workflow.  Everything else looks to be running well!

**Comment by mwengren** [comment]
Closed by 499d69e44aaad7e803b03dba477df2de4d16d379
